version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    labels: [dependencies, security]
    commit-message:
      prefix: deps
  - package-ecosystem: cargo
    directory: /rust
    schedule:
      interval: daily
    labels: [dependencies, security]
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
  - package-ecosystem: npm
    directory: /.github/eslint-security
    schedule:
      interval: weekly
    labels: [dependencies, security]
    commit-message:
      prefix: deps
  - package-ecosystem: pip
    directory: /.github/ci
    schedule:
      interval: weekly
    labels: [dependencies, security]
    commit-message:
      prefix: deps
