use std::{
    ops::Deref,
    str::FromStr,
    time::{Duration, SystemTime, UNIX_EPOCH},
};

use sqlx::{
    postgres::{PgConnectOptions, PgPoolOptions},
    PgPool,
};

use crate::CentralDbError;

const TEST_DSN_ENV_VARS: [&str; 3] = ["CENTRAL_TEST_DSN", "DATABASE_URL", "DEADLOCK_CENTRAL_DSN"];

pub struct TestDb {
    pool: Option<PgPool>,
    admin_options: PgConnectOptions,
    db_name: String,
}

impl TestDb {
    pub fn pool(&self) -> &PgPool {
        self.pool
            .as_ref()
            .expect("TestDb pool must be available until drop")
    }
}

impl Deref for TestDb {
    type Target = PgPool;

    fn deref(&self) -> &Self::Target {
        self.pool()
    }
}

impl Drop for TestDb {
    fn drop(&mut self) {
        let Some(pool) = self.pool.take() else {
            return;
        };

        let admin_options = self.admin_options.clone();
        let db_name = std::mem::take(&mut self.db_name);
        if db_name.is_empty() {
            return;
        }

        let thread = std::thread::Builder::new()
            .name("dl-central-testdb-drop".to_string())
            .spawn(move || {
                let runtime = match tokio::runtime::Builder::new_current_thread()
                    .enable_all()
                    .build()
                {
                    Ok(runtime) => runtime,
                    Err(err) => {
                        eprintln!("failed to build TestDb teardown runtime for {db_name}: {err}");
                        return;
                    }
                };

                runtime.block_on(async move {
                    if tokio::time::timeout(Duration::from_secs(5), pool.close())
                        .await
                        .is_err()
                    {
                        eprintln!(
                            "timed out closing TestDb pool for {db_name}; forcing database teardown"
                        );
                    }

                    let admin_pool = match PgPoolOptions::new()
                        .max_connections(1)
                        .connect_with(admin_options)
                        .await
                    {
                        Ok(pool) => pool,
                        Err(err) => {
                            eprintln!(
                                "failed to open fresh admin connection for TestDb teardown of {db_name}: {err}"
                            );
                            return;
                        }
                    };

                    if let Err(err) = drop_database(&admin_pool, &db_name).await {
                        eprintln!("failed to drop TestDb database {db_name}: {err}");
                    }

                    admin_pool.close().await;
                });
            });

        match thread {
            Ok(handle) => {
                if handle.join().is_err() {
                    eprintln!("TestDb teardown thread panicked");
                }
            }
            Err(err) => eprintln!("failed to spawn TestDb teardown thread: {err}"),
        }
    }
}

pub async fn test_pool() -> Result<TestDb, CentralDbError> {
    let dsn = test_dsn_from_env()?;
    let admin_options = PgConnectOptions::from_str(&dsn)?;
    let db_name = unique_db_name();

    let admin_pool = PgPoolOptions::new()
        .max_connections(1)
        .connect_with(admin_options.clone())
        .await?;

    create_database(&admin_pool, &db_name).await?;

    let test_options = admin_options.clone().database(&db_name);
    let pool_result = PgPoolOptions::new()
        .max_connections(4)
        .connect_with(test_options)
        .await;

    let pool = match pool_result {
        Ok(pool) => pool,
        Err(err) => {
            let _ = drop_database(&admin_pool, &db_name).await;
            admin_pool.close().await;
            return Err(err.into());
        }
    };

    if let Err(err) = sqlx::migrate!("./migrations").run(&pool).await {
        pool.close().await;
        let _ = drop_database(&admin_pool, &db_name).await;
        admin_pool.close().await;
        return Err(err.into());
    }

    admin_pool.close().await;

    Ok(TestDb {
        pool: Some(pool),
        admin_options,
        db_name,
    })
}

fn test_dsn_from_env() -> Result<String, CentralDbError> {
    TEST_DSN_ENV_VARS
        .iter()
        .find_map(|name| std::env::var(name).ok())
        .ok_or_else(|| {
            CentralDbError::TestHarness(format!(
                "eine der Umgebungsvariablen {} muss gesetzt sein",
                TEST_DSN_ENV_VARS.join(", ")
            ))
        })
}

fn unique_db_name() -> String {
    let nanos = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_or(0, |duration| duration.as_nanos());

    format!("dlcentral_test_{}_{}", std::process::id(), nanos)
}

async fn create_database(pool: &PgPool, db_name: &str) -> Result<(), CentralDbError> {
    // The identifier is generated by this harness from a fixed prefix plus a
    // process/time suffix; still validate before interpolating into SQL.
    let ident = quoted_ident(db_name)?;
    sqlx::query(&format!("CREATE DATABASE {ident}"))
        .execute(pool)
        .await?;

    Ok(())
}

async fn drop_database(pool: &PgPool, db_name: &str) -> Result<(), CentralDbError> {
    let ident = quoted_ident(db_name)?;
    let terminate_result = terminate_database_sessions(pool, db_name).await;
    let drop_result = sqlx::query(&format!("DROP DATABASE IF EXISTS {ident} WITH (FORCE)"))
        .execute(pool)
        .await;

    match (terminate_result, drop_result) {
        (Ok(()), Ok(_)) => Ok(()),
        (Err(err), Ok(_)) => Err(err),
        (Ok(()), Err(err)) => Err(err.into()),
        (Err(terminate_err), Err(drop_err)) => Err(CentralDbError::TestHarness(format!(
            "Test-Datenbank-Teardown unvollstaendig: Sessions terminieren fehlgeschlagen: {terminate_err}; DROP DATABASE fehlgeschlagen: {drop_err}"
        ))),
    }
}

async fn terminate_database_sessions(pool: &PgPool, db_name: &str) -> Result<(), CentralDbError> {
    sqlx::query(
        "SELECT pg_terminate_backend(pid) \
         FROM pg_stat_activity \
         WHERE datname = $1 AND pid <> pg_backend_pid()",
    )
    .bind(db_name)
    .execute(pool)
    .await?;

    Ok(())
}

fn quoted_ident(ident: &str) -> Result<String, CentralDbError> {
    let valid = !ident.is_empty()
        && ident
            .bytes()
            .all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'_');

    if valid {
        Ok(format!(r#""{ident}""#))
    } else {
        Err(CentralDbError::TestHarness(format!(
            "ungueltiger Test-Datenbankname: {ident}"
        )))
    }
}
