CREATE SCHEMA IF NOT EXISTS steam;

CREATE TABLE IF NOT EXISTS steam.beta_invite_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT,
    discord_id BIGINT NOT NULL,
    discord_name TEXT,
    steam_id64 BIGINT NOT NULL,
    steam_profile TEXT NOT NULL,
    invited_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS beta_invite_audit_discord_idx
    ON steam.beta_invite_audit (discord_id);

CREATE INDEX IF NOT EXISTS beta_invite_audit_steam_idx
    ON steam.beta_invite_audit (steam_id64);

CREATE TABLE IF NOT EXISTS steam.beta_invite_auto_failure_alerts (
    discord_id BIGINT PRIMARY KEY,
    last_alert_at TIMESTAMPTZ NOT NULL,
    last_error TEXT
);

CREATE TABLE IF NOT EXISTS steam.beta_invite_friendship_auto_poll (
    discord_id BIGINT PRIMARY KEY,
    invite_record_id BIGINT NOT NULL,
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    steam_id64 BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT true,
    started_at TIMESTAMPTZ NOT NULL,
    next_check_at TIMESTAMPTZ NOT NULL,
    attempts_completed INTEGER NOT NULL DEFAULT 0,
    max_attempts INTEGER NOT NULL DEFAULT 5,
    last_checked_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    last_error TEXT
);

CREATE INDEX IF NOT EXISTS beta_invite_friendship_auto_poll_channel_idx
    ON steam.beta_invite_friendship_auto_poll (channel_id);

CREATE INDEX IF NOT EXISTS beta_invite_friendship_auto_poll_due_idx
    ON steam.beta_invite_friendship_auto_poll (active, next_check_at);

CREATE TABLE IF NOT EXISTS steam.beta_invite_intent (
    discord_id BIGINT PRIMARY KEY,
    intent TEXT NOT NULL,
    decided_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    locked BOOLEAN NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS steam.beta_invite_panel_clicks (
    discord_id BIGINT PRIMARY KEY,
    click_count INTEGER NOT NULL DEFAULT 1,
    first_clicked_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_clicked_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS steam.beta_invite_pending_payments (
    discord_id BIGINT PRIMARY KEY,
    discord_name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    token TEXT,
    paid_at TIMESTAMPTZ,
    consumed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS beta_invite_pending_payments_created_at_idx
    ON steam.beta_invite_pending_payments (created_at);

CREATE UNIQUE INDEX IF NOT EXISTS beta_invite_pending_payments_token_uq
    ON steam.beta_invite_pending_payments (token)
    WHERE token IS NOT NULL;

CREATE TABLE IF NOT EXISTS steam.beta_invite_supporter_role_grants (
    discord_id BIGINT PRIMARY KEY,
    role_id BIGINT NOT NULL,
    granted_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    last_payment_at TIMESTAMPTZ NOT NULL,
    last_applied_at TIMESTAMPTZ,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS beta_invite_supporter_role_grants_expires_idx
    ON steam.beta_invite_supporter_role_grants (expires_at, revoked_at);

CREATE TABLE IF NOT EXISTS steam.beta_invite_tickets (
    discord_id BIGINT PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    status TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    closed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS beta_invite_tickets_channel_idx
    ON steam.beta_invite_tickets (channel_id);

CREATE TABLE IF NOT EXISTS steam.steam_beta_invites (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_id BIGINT NOT NULL,
    steam_id64 BIGINT NOT NULL,
    account_id BIGINT,
    status TEXT NOT NULL,
    last_error TEXT,
    friend_requested_at TIMESTAMPTZ,
    friend_confirmed_at TIMESTAMPTZ,
    invite_sent_at TIMESTAMPTZ,
    last_notified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    scheduled_invite_at TIMESTAMPTZ,
    dispatch_attempts INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT steam_beta_invites_discord_id_uq UNIQUE (discord_id),
    CONSTRAINT steam_beta_invites_steam_id64_uq UNIQUE (steam_id64)
);

CREATE INDEX IF NOT EXISTS steam_beta_invites_account_idx
    ON steam.steam_beta_invites (account_id);

CREATE INDEX IF NOT EXISTS steam_beta_invites_status_idx
    ON steam.steam_beta_invites (status);

CREATE INDEX IF NOT EXISTS steam_beta_invites_status_schedule_idx
    ON steam.steam_beta_invites (status, scheduled_invite_at, updated_at);

CREATE TABLE IF NOT EXISTS steam.steam_cleanup_poll_state (
    user_id BIGINT PRIMARY KEY,
    last_polled_at TIMESTAMPTZ NOT NULL,
    last_result TEXT NOT NULL,
    last_error TEXT,
    updated_at TIMESTAMPTZ NOT NULL,
    miss_count INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS steam_cleanup_poll_state_polled_idx
    ON steam.steam_cleanup_poll_state (last_polled_at, updated_at);

CREATE TABLE IF NOT EXISTS steam.steam_flow_throttle (
    key TEXT PRIMARY KEY,
    last_run TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS steam.steam_friend_check_cache (
    steam_id BIGINT PRIMARY KEY,
    friend BOOLEAN NOT NULL,
    checked_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS steam.steam_friend_requests (
    steam_id BIGINT PRIMARY KEY,
    status TEXT DEFAULT 'pending',
    requested_at TIMESTAMPTZ DEFAULT now(),
    last_attempt TIMESTAMPTZ,
    attempts INTEGER DEFAULT 0,
    error TEXT
);

CREATE INDEX IF NOT EXISTS steam_friend_requests_status_idx
    ON steam.steam_friend_requests (status);

CREATE TABLE IF NOT EXISTS steam.steam_friendship_miss_tracker (
    steam_id BIGINT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    miss_count INTEGER NOT NULL DEFAULT 0,
    last_polled_at TIMESTAMPTZ NOT NULL,
    last_seen_friend_at TIMESTAMPTZ,
    last_miss_at TIMESTAMPTZ,
    last_action_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS steam_friendship_miss_tracker_polled_idx
    ON steam.steam_friendship_miss_tracker (last_polled_at, miss_count);

CREATE INDEX IF NOT EXISTS steam_friendship_miss_tracker_user_idx
    ON steam.steam_friendship_miss_tracker (user_id, last_polled_at);

CREATE TABLE IF NOT EXISTS steam.steam_launch_tokens (
    token TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    consumed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS steam_launch_tokens_expires_idx
    ON steam.steam_launch_tokens (expires_at);

CREATE INDEX IF NOT EXISTS steam_launch_tokens_user_idx
    ON steam.steam_launch_tokens (user_id, expires_at);

CREATE TABLE IF NOT EXISTS steam.steam_links_archive (
    user_id BIGINT NOT NULL,
    steam_id BIGINT NOT NULL,
    name TEXT,
    verified BOOLEAN DEFAULT false,
    primary_account BOOLEAN DEFAULT false,
    deadlock_rank INTEGER,
    deadlock_rank_name TEXT,
    deadlock_subrank INTEGER,
    deadlock_badge_level INTEGER,
    deadlock_rank_updated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ,
    left_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    guild_id BIGINT,
    leave_reason TEXT,
    display_name TEXT,
    PRIMARY KEY (user_id, steam_id)
);

CREATE INDEX IF NOT EXISTS steam_links_archive_steam_idx
    ON steam.steam_links_archive (steam_id);

CREATE INDEX IF NOT EXISTS steam_links_archive_user_left_idx
    ON steam.steam_links_archive (user_id, left_at);

CREATE TABLE IF NOT EXISTS steam.steam_links_leave_archive (
    user_id BIGINT NOT NULL,
    steam_id BIGINT NOT NULL,
    name TEXT,
    verified BOOLEAN DEFAULT false,
    primary_account BOOLEAN DEFAULT false,
    deadlock_rank INTEGER,
    deadlock_rank_name TEXT,
    deadlock_subrank INTEGER,
    deadlock_badge_level INTEGER,
    deadlock_rank_updated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    left_at TIMESTAMPTZ,
    guild_id BIGINT,
    leave_reason TEXT,
    display_name TEXT,
    PRIMARY KEY (user_id, steam_id)
);

CREATE INDEX IF NOT EXISTS steam_links_leave_archive_user_left_idx
    ON steam.steam_links_leave_archive (user_id, left_at);

CREATE TABLE IF NOT EXISTS steam.steam_nudge_state (
    user_id BIGINT PRIMARY KEY,
    notified_at TIMESTAMPTZ,
    opt_out BOOLEAN DEFAULT false,
    first_seen TIMESTAMPTZ DEFAULT now(),
    message_id BIGINT,
    channel_id BIGINT,
    view_version INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS steam_nudge_state_opt_out_idx
    ON steam.steam_nudge_state (opt_out);

CREATE TABLE IF NOT EXISTS steam.steam_presence_watchlist (
    steam_id BIGINT PRIMARY KEY,
    note TEXT,
    added_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS steam.steam_quick_invites (
    token TEXT PRIMARY KEY,
    invite_link TEXT NOT NULL,
    invite_limit INTEGER DEFAULT 1,
    invite_duration INTEGER,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ,
    status TEXT DEFAULT 'available',
    reserved_by BIGINT,
    reserved_at TIMESTAMPTZ,
    last_seen TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS steam_quick_invites_reserved_idx
    ON steam.steam_quick_invites (reserved_by);

CREATE INDEX IF NOT EXISTS steam_quick_invites_status_idx
    ON steam.steam_quick_invites (status, expires_at);

CREATE TABLE IF NOT EXISTS steam.steam_rank_assignments (
    user_id BIGINT NOT NULL,
    guild_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, guild_id)
);

CREATE INDEX IF NOT EXISTS steam_rank_assignments_guild_idx
    ON steam.steam_rank_assignments (guild_id);

CREATE TABLE IF NOT EXISTS steam.steam_rank_history (
    user_id BIGINT NOT NULL,
    badge_level INTEGER,
    rank_name TEXT,
    captured_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS steam_rank_history_user_captured_idx
    ON steam.steam_rank_history (user_id, captured_at);

CREATE TABLE IF NOT EXISTS steam.steam_rich_presence (
    steam_id BIGINT PRIMARY KEY,
    app_id BIGINT,
    status TEXT,
    status_text TEXT,
    display TEXT,
    player_group TEXT,
    player_group_size INTEGER,
    connect TEXT,
    mode TEXT,
    map TEXT,
    party_size INTEGER,
    raw_json JSONB,
    last_update TIMESTAMPTZ,
    updated_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS steam.steam_role_cleanup_pending (
    user_id BIGINT PRIMARY KEY,
    reason TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    last_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS steam_role_cleanup_pending_updated_idx
    ON steam.steam_role_cleanup_pending (updated_at);

CREATE TABLE IF NOT EXISTS steam.steam_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    payload JSONB,
    status TEXT NOT NULL DEFAULT 'PENDING',
    result JSONB,
    error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ,
    attempts INTEGER DEFAULT 0
);

CREATE INDEX IF NOT EXISTS steam_tasks_attempts_idx
    ON steam.steam_tasks (attempts);

CREATE INDEX IF NOT EXISTS steam_tasks_created_idx
    ON steam.steam_tasks (created_at);

CREATE INDEX IF NOT EXISTS steam_tasks_status_idx
    ON steam.steam_tasks (status, id);

CREATE INDEX IF NOT EXISTS steam_tasks_updated_idx
    ON steam.steam_tasks (updated_at);
