CREATE TABLE IF NOT EXISTS voice.deadlock_party_members (
    party_id TEXT NOT NULL,
    steam_id TEXT NOT NULL,
    party_size INTEGER,
    seen_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (party_id, steam_id)
);

CREATE INDEX IF NOT EXISTS deadlock_party_members_steam_id_idx
    ON voice.deadlock_party_members (steam_id);

CREATE INDEX IF NOT EXISTS deadlock_party_members_seen_at_idx
    ON voice.deadlock_party_members (seen_at);

CREATE TABLE IF NOT EXISTS voice.deadlock_subrank_roles (
    guild_id BIGINT NOT NULL,
    rank_value INTEGER NOT NULL,
    subrank INTEGER NOT NULL,
    role_id BIGINT NOT NULL,
    role_name TEXT,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (guild_id, rank_value, subrank)
);

CREATE UNIQUE INDEX IF NOT EXISTS deadlock_subrank_roles_guild_role_idx
    ON voice.deadlock_subrank_roles (guild_id, role_id);

CREATE TABLE IF NOT EXISTS voice.deadlock_voice_watch (
    steam_id TEXT PRIMARY KEY,
    guild_id BIGINT,
    channel_id BIGINT,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS deadlock_voice_watch_guild_channel_idx
    ON voice.deadlock_voice_watch (guild_id, channel_id);

CREATE TABLE IF NOT EXISTS voice.rename_global_state (
    id BIGINT PRIMARY KEY DEFAULT 1,
    last_rename_timestamp TIMESTAMPTZ DEFAULT (now() - INTERVAL '5 minutes'),
    next_worker_id INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS voice.rename_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT NOT NULL,
    new_name TEXT NOT NULL,
    reason TEXT,
    status TEXT NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMPTZ DEFAULT now(),
    processed_at TIMESTAMPTZ,
    retry_count INTEGER DEFAULT 0,
    last_error TEXT,
    assigned_worker_id BIGINT DEFAULT 0
);

CREATE INDEX IF NOT EXISTS rename_requests_status_created_at_idx
    ON voice.rename_requests (status, created_at);

CREATE INDEX IF NOT EXISTS rename_requests_channel_id_idx
    ON voice.rename_requests (channel_id);

CREATE INDEX IF NOT EXISTS rename_requests_assigned_worker_id_idx
    ON voice.rename_requests (assigned_worker_id);

CREATE TABLE IF NOT EXISTS voice.router_user_prefs (
    user_id BIGINT PRIMARY KEY,
    mode TEXT NOT NULL CHECK (mode IN ('ranked', 'casual', 'street_brawl')),
    auto_join BOOLEAN NOT NULL DEFAULT false,
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS router_user_prefs_mode_idx
    ON voice.router_user_prefs (mode);

CREATE TABLE IF NOT EXISTS voice.tempvoice_bans (
    owner_id BIGINT NOT NULL,
    banned_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (owner_id, banned_id)
);

CREATE INDEX IF NOT EXISTS tempvoice_bans_banned_id_idx
    ON voice.tempvoice_bans (banned_id);

CREATE TABLE IF NOT EXISTS voice.tempvoice_interface (
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    message_id BIGINT NOT NULL,
    category_id BIGINT,
    lane_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (guild_id, message_id),
    UNIQUE (lane_id)
);

CREATE INDEX IF NOT EXISTS tempvoice_interface_channel_id_idx
    ON voice.tempvoice_interface (channel_id);

CREATE INDEX IF NOT EXISTS tempvoice_interface_category_id_idx
    ON voice.tempvoice_interface (category_id);

CREATE TABLE IF NOT EXISTS voice.tempvoice_lane_tag_filter (
    channel_id BIGINT PRIMARY KEY,
    min_age_tag TEXT,
    required_tone_tag TEXT,
    deny_ragebaiter BOOLEAN DEFAULT false,
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS voice.tempvoice_lanes (
    channel_id BIGINT PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    owner_id BIGINT NOT NULL,
    base_name TEXT NOT NULL,
    category_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    source_staging_id BIGINT,
    initial_owner_id BIGINT
);

CREATE INDEX IF NOT EXISTS tempvoice_lanes_guild_id_idx
    ON voice.tempvoice_lanes (guild_id);

CREATE INDEX IF NOT EXISTS tempvoice_lanes_owner_id_idx
    ON voice.tempvoice_lanes (owner_id);

CREATE INDEX IF NOT EXISTS tempvoice_lanes_category_id_idx
    ON voice.tempvoice_lanes (category_id);

CREATE INDEX IF NOT EXISTS tempvoice_lanes_source_staging_id_idx
    ON voice.tempvoice_lanes (source_staging_id);

CREATE TABLE IF NOT EXISTS voice.tempvoice_lurkers (
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    original_nick TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (channel_id, user_id)
);

CREATE INDEX IF NOT EXISTS tempvoice_lurkers_guild_id_idx
    ON voice.tempvoice_lurkers (guild_id);

CREATE INDEX IF NOT EXISTS tempvoice_lurkers_user_id_idx
    ON voice.tempvoice_lurkers (user_id);

CREATE TABLE IF NOT EXISTS voice.tempvoice_owner_prefs (
    owner_id BIGINT PRIMARY KEY,
    region TEXT NOT NULL CHECK (region IN ('DE', 'EU')),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS voice.tempvoice_presets (
    user_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    name TEXT NOT NULL,
    base_name TEXT NOT NULL,
    member_limit INTEGER NOT NULL,
    min_rank TEXT NOT NULL DEFAULT 'unknown',
    region TEXT NOT NULL DEFAULT 'EU' CHECK (region IN ('DE', 'EU')),
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (user_id, category_id, name)
);

CREATE INDEX IF NOT EXISTS tempvoice_presets_category_id_idx
    ON voice.tempvoice_presets (category_id);

CREATE TABLE IF NOT EXISTS voice.tempvoice_rank_pref (
    user_id BIGINT PRIMARY KEY,
    rank TEXT NOT NULL DEFAULT 'unknown',
    subrank INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS voice.tempvoice_staging_channels (
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (guild_id, channel_id)
);

CREATE INDEX IF NOT EXISTS tempvoice_staging_channels_channel_id_idx
    ON voice.tempvoice_staging_channels (channel_id);

CREATE TABLE IF NOT EXISTS voice.voice_channel_anchors (
    channel_id BIGINT PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    rank_name TEXT NOT NULL,
    rank_value INTEGER NOT NULL,
    allowed_min INTEGER NOT NULL,
    allowed_max INTEGER NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    anchor_subrank INTEGER DEFAULT 3,
    score_min INTEGER,
    score_max INTEGER
);

CREATE INDEX IF NOT EXISTS voice_channel_anchors_guild_id_idx
    ON voice.voice_channel_anchors (guild_id);

CREATE INDEX IF NOT EXISTS voice_channel_anchors_user_id_idx
    ON voice.voice_channel_anchors (user_id);

CREATE INDEX IF NOT EXISTS voice_channel_anchors_rank_idx
    ON voice.voice_channel_anchors (rank_value, anchor_subrank);

CREATE TABLE IF NOT EXISTS voice.voice_channel_settings (
    channel_id BIGINT PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS voice_channel_settings_guild_enabled_idx
    ON voice.voice_channel_settings (guild_id, enabled);

CREATE TABLE IF NOT EXISTS voice.voice_stats (
    user_id BIGINT PRIMARY KEY,
    total_seconds BIGINT NOT NULL DEFAULT 0,
    last_update TIMESTAMPTZ DEFAULT now(),
    total_points BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS voice_stats_total_points_idx
    ON voice.voice_stats (total_points DESC);

CREATE INDEX IF NOT EXISTS voice_stats_total_seconds_idx
    ON voice.voice_stats (total_seconds DESC);
