CREATE TABLE IF NOT EXISTS tierlist.deadlock_heroes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hero_id BIGINT NOT NULL,
    name TEXT NOT NULL,
    origin_build_id BIGINT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    target_build_name_override TEXT,
    UNIQUE (hero_id),
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS tierlist.deadlock_hero_builds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hero_id BIGINT NOT NULL,
    build_id BIGINT NOT NULL,
    build_name TEXT NOT NULL,
    author_name TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    sort_order INTEGER NOT NULL DEFAULT 100,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    sync_status TEXT,
    sync_message TEXT,
    last_checked_at TIMESTAMPTZ,
    last_synced_at TIMESTAMPTZ,
    last_alerted_at TIMESTAMPTZ,
    source_version BIGINT,
    source_last_updated_at TIMESTAMPTZ,
    clone_build_id BIGINT,
    clone_version BIGINT,
    UNIQUE (hero_id, build_id)
);

CREATE TABLE IF NOT EXISTS tierlist.hero_build_sources (
    hero_build_id BIGINT PRIMARY KEY,
    origin_build_id BIGINT,
    author_account_id BIGINT NOT NULL,
    hero_id BIGINT NOT NULL,
    language INTEGER NOT NULL,
    version BIGINT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    tags JSONB,
    details JSONB,
    published_at TIMESTAMPTZ,
    last_updated_at TIMESTAMPTZ,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tierlist.hero_build_clones (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    origin_hero_build_id BIGINT NOT NULL,
    origin_build_id BIGINT,
    hero_id BIGINT NOT NULL,
    author_account_id BIGINT,
    source_language INTEGER,
    source_version BIGINT,
    source_last_updated_at TIMESTAMPTZ,
    target_language INTEGER NOT NULL,
    target_name TEXT,
    target_description TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    status_info TEXT,
    uploaded_build_id BIGINT,
    uploaded_version BIGINT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_attempt_at TIMESTAMPTZ,
    attempts INTEGER NOT NULL DEFAULT 0,
    UNIQUE (origin_hero_build_id, target_language)
);

CREATE TABLE IF NOT EXISTS tierlist.tierlist_settings (
    k TEXT PRIMARY KEY,
    v TEXT NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tierlist.tierlist_hero_meta (
    hero_id BIGINT PRIMARY KEY,
    description TEXT NOT NULL DEFAULT '',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tierlist.tierlist_streamers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hero_id BIGINT NOT NULL,
    twitch_login TEXT NOT NULL,
    display_name TEXT NOT NULL,
    sort_order INTEGER NOT NULL DEFAULT 100,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (hero_id, twitch_login)
);

CREATE TABLE IF NOT EXISTS tierlist.tierlist_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bucket TEXT NOT NULL,
    patch_id TEXT NOT NULL,
    patch_at TIMESTAMPTZ NOT NULL,
    fetched_at TIMESTAMPTZ NOT NULL,
    UNIQUE (bucket, fetched_at)
);

CREATE TABLE IF NOT EXISTS tierlist.tierlist_snapshot_heroes (
    snapshot_id BIGINT NOT NULL REFERENCES tierlist.tierlist_snapshots(id) ON DELETE CASCADE,
    hero_id BIGINT NOT NULL,
    matches BIGINT NOT NULL,
    wins BIGINT NOT NULL,
    losses BIGINT NOT NULL,
    winrate DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (snapshot_id, hero_id)
);

CREATE TABLE IF NOT EXISTS tierlist.tierlist_build_votes (
    build_id BIGINT PRIMARY KEY,
    upvotes BIGINT NOT NULL DEFAULT 0,
    downvotes BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tierlist.watched_build_authors (
    author_account_id BIGINT PRIMARY KEY,
    notes TEXT,
    is_active BOOLEAN NOT NULL DEFAULT true,
    last_checked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    priority INTEGER,
    last_checked_status TEXT,
    last_checked_message TEXT
);

CREATE TABLE IF NOT EXISTS tierlist.meta_heroes (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    tier TEXT DEFAULT 'C',
    role TEXT,
    image_url TEXT,
    abilities JSONB,
    stats JSONB,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tierlist.meta_builds (
    id TEXT PRIMARY KEY,
    hero_id TEXT REFERENCES tierlist.meta_heroes(id),
    name TEXT NOT NULL,
    author_id TEXT,
    author_name TEXT,
    description TEXT,
    ability_order JSONB,
    items JSONB,
    upvotes BIGINT DEFAULT 0,
    downvotes BIGINT DEFAULT 0,
    status TEXT DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tierlist.meta_items (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT,
    stats JSONB,
    image_url TEXT
);

CREATE TABLE IF NOT EXISTS tierlist.meta_tier_lists (
    id TEXT PRIMARY KEY,
    name TEXT,
    owner_id TEXT,
    is_public BOOLEAN DEFAULT false,
    secret_code TEXT,
    tiers JSONB,
    forked_from TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS tierlist.meta_votes (
    id TEXT PRIMARY KEY,
    user_id TEXT,
    build_id TEXT,
    vote_type TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (user_id, build_id)
);

CREATE TABLE IF NOT EXISTS tierlist.meta_tier_history (
    id TEXT PRIMARY KEY,
    hero_id TEXT,
    hero_name TEXT,
    old_tier TEXT,
    new_tier TEXT,
    changed_by TEXT,
    changed_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_deadlock_heroes_active
    ON tierlist.deadlock_heroes (is_active, hero_id);
CREATE INDEX IF NOT EXISTS idx_deadlock_heroes_hero
    ON tierlist.deadlock_heroes (hero_id);
CREATE INDEX IF NOT EXISTS idx_deadlock_hero_builds_build_id
    ON tierlist.deadlock_hero_builds (build_id);
CREATE INDEX IF NOT EXISTS idx_deadlock_hero_builds_hero_active_sort
    ON tierlist.deadlock_hero_builds (hero_id, is_active, sort_order);
CREATE INDEX IF NOT EXISTS idx_deadlock_hero_builds_sync_status
    ON tierlist.deadlock_hero_builds (sync_status, last_alerted_at);
CREATE INDEX IF NOT EXISTS idx_hero_build_sources_author
    ON tierlist.hero_build_sources (author_account_id);
CREATE INDEX IF NOT EXISTS idx_hero_build_sources_hero
    ON tierlist.hero_build_sources (hero_id);
CREATE INDEX IF NOT EXISTS idx_hero_build_sources_origin
    ON tierlist.hero_build_sources (origin_build_id);
CREATE INDEX IF NOT EXISTS idx_hero_build_clones_origin
    ON tierlist.hero_build_clones (origin_hero_build_id, target_language);
CREATE INDEX IF NOT EXISTS idx_hero_build_clones_status
    ON tierlist.hero_build_clones (status, hero_id);
CREATE INDEX IF NOT EXISTS idx_hero_build_clones_status_hero
    ON tierlist.hero_build_clones (status, hero_id, created_at);
CREATE INDEX IF NOT EXISTS idx_tierlist_snapshots_bucket_fetched
    ON tierlist.tierlist_snapshots (bucket, fetched_at DESC);
CREATE INDEX IF NOT EXISTS idx_tierlist_snapshot_heroes_snapshot
    ON tierlist.tierlist_snapshot_heroes (snapshot_id);
CREATE INDEX IF NOT EXISTS idx_tierlist_streamers_hero_active_sort
    ON tierlist.tierlist_streamers (hero_id, is_active, sort_order);
CREATE INDEX IF NOT EXISTS idx_watched_build_authors_active_priority
    ON tierlist.watched_build_authors (is_active, priority);
CREATE INDEX IF NOT EXISTS idx_meta_builds_hero
    ON tierlist.meta_builds (hero_id);
CREATE INDEX IF NOT EXISTS idx_meta_builds_status
    ON tierlist.meta_builds (status);
CREATE INDEX IF NOT EXISTS idx_meta_tier_lists_public_created
    ON tierlist.meta_tier_lists (is_public, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_meta_tier_lists_owner_created
    ON tierlist.meta_tier_lists (owner_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_meta_tier_history_changed
    ON tierlist.meta_tier_history (changed_at DESC);
CREATE INDEX IF NOT EXISTS idx_meta_votes_build
    ON tierlist.meta_votes (build_id);
