CREATE TABLE IF NOT EXISTS bot.changelog_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL,
    section TEXT,
    subject TEXT,
    subject_type TEXT,
    change_text TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS changelog_entries_post_id_idx
    ON bot.changelog_entries (post_id);

CREATE TABLE IF NOT EXISTS bot.claimed_threads (
    thread_id BIGINT PRIMARY KEY,
    assigned_user_id BIGINT,
    claimed_by_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS claimed_threads_assigned_user_id_idx
    ON bot.claimed_threads (assigned_user_id);

CREATE INDEX IF NOT EXISTS claimed_threads_claimed_by_id_idx
    ON bot.claimed_threads (claimed_by_id);

CREATE TABLE IF NOT EXISTS bot.customgames_tournament_teams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    name TEXT NOT NULL,
    name_key TEXT NOT NULL,
    created_by BIGINT,
    created_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (guild_id, name_key)
);

CREATE TABLE IF NOT EXISTS bot.customgames_tournament_signups (
    guild_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    registration_mode TEXT NOT NULL CHECK (registration_mode IN ('solo', 'team')),
    rank TEXT NOT NULL,
    rank_value INTEGER NOT NULL,
    team_id BIGINT REFERENCES bot.customgames_tournament_teams(id) ON DELETE SET NULL,
    assigned_by_admin BOOLEAN NOT NULL DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    rank_subvalue INTEGER NOT NULL DEFAULT 0,
    display_name TEXT,
    PRIMARY KEY (guild_id, user_id)
);

CREATE INDEX IF NOT EXISTS customgames_tournament_signups_team_id_idx
    ON bot.customgames_tournament_signups (team_id);

CREATE TABLE IF NOT EXISTS bot.discord_invite_codes (
    guild_id BIGINT NOT NULL,
    invite_code TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    last_seen_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY (guild_id, invite_code)
);

CREATE TABLE IF NOT EXISTS bot.dm_response_tracking (
    user_id BIGINT PRIMARY KEY,
    last_dm_sent TIMESTAMPTZ NOT NULL,
    response_count INTEGER DEFAULT 0,
    last_response TIMESTAMPTZ,
    status TEXT DEFAULT 'pending'
);

CREATE TABLE IF NOT EXISTS bot.faq_chat_sessions (
    session_id TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    user_name TEXT,
    channel_id BIGINT NOT NULL,
    guild_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now(),
    expires_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL DEFAULT 'active',
    last_activity_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS faq_chat_sessions_user_id_idx
    ON bot.faq_chat_sessions (user_id);

CREATE INDEX IF NOT EXISTS faq_chat_sessions_expires_at_idx
    ON bot.faq_chat_sessions (expires_at);

CREATE TABLE IF NOT EXISTS bot.faq_chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES bot.faq_chat_sessions(session_id) ON DELETE CASCADE,
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS faq_chat_messages_session_id_idx
    ON bot.faq_chat_messages (session_id);

CREATE TABLE IF NOT EXISTS bot.invite_snapshot_cache (
    guild_id BIGINT PRIMARY KEY,
    snapshot_json JSONB NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bot.issue_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    guild_id BIGINT,
    channel_id BIGINT,
    message_id BIGINT,
    category TEXT,
    title TEXT,
    description TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    ai_response TEXT,
    ai_model TEXT,
    ai_error TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    answered_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS issue_reports_user_id_idx
    ON bot.issue_reports (user_id);

CREATE INDEX IF NOT EXISTS issue_reports_status_idx
    ON bot.issue_reports (status);

CREATE TABLE IF NOT EXISTS bot.kv_store (
    ns TEXT NOT NULL,
    k TEXT NOT NULL,
    v TEXT NOT NULL,
    PRIMARY KEY (ns, k)
);

CREATE TABLE IF NOT EXISTS bot.notification_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    rank TEXT NOT NULL,
    notification_time TIMESTAMPTZ DEFAULT now(),
    count INTEGER DEFAULT 1
);

CREATE INDEX IF NOT EXISTS notification_log_user_id_idx
    ON bot.notification_log (user_id);

CREATE TABLE IF NOT EXISTS bot.notification_queue (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    guild_id BIGINT NOT NULL,
    rank TEXT NOT NULL,
    queue_date DATE NOT NULL,
    added_at TIMESTAMPTZ DEFAULT now(),
    processed BOOLEAN DEFAULT false
);

CREATE INDEX IF NOT EXISTS notification_queue_pending_idx
    ON bot.notification_queue (queue_date, guild_id)
    WHERE processed IS DISTINCT FROM true;

CREATE TABLE IF NOT EXISTS bot.oauth_states (
    state TEXT PRIMARY KEY,
    provider TEXT NOT NULL,
    flow_type TEXT NOT NULL,
    requesting_service TEXT,
    redirect_after TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    used BOOLEAN DEFAULT false,
    metadata JSONB
);

CREATE INDEX IF NOT EXISTS oauth_states_expires_at_idx
    ON bot.oauth_states (expires_at);

CREATE TABLE IF NOT EXISTS bot.onboarding_pending_verify (
    user_id BIGINT PRIMARY KEY,
    channel_id BIGINT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bot.persistent_views (
    message_id BIGINT PRIMARY KEY,
    channel_id BIGINT NOT NULL,
    guild_id BIGINT NOT NULL,
    view_type TEXT NOT NULL,
    user_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS persistent_views_view_type_idx
    ON bot.persistent_views (view_type);

CREATE TABLE IF NOT EXISTS bot.reaction_role_mappings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    source_channel_id BIGINT NOT NULL,
    message_id BIGINT NOT NULL,
    emoji TEXT NOT NULL,
    role_id BIGINT NOT NULL,
    dm_enabled BOOLEAN NOT NULL DEFAULT false,
    dm_text TEXT,
    remove_on_unreact BOOLEAN NOT NULL DEFAULT true,
    backfill_pending BOOLEAN NOT NULL DEFAULT false,
    active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS reaction_role_mappings_message_emoji_idx
    ON bot.reaction_role_mappings (message_id, emoji);

CREATE INDEX IF NOT EXISTS reaction_role_mappings_active_idx
    ON bot.reaction_role_mappings (active, backfill_pending);

CREATE TABLE IF NOT EXISTS bot.reaction_role_dm_log (
    mapping_id BIGINT NOT NULL REFERENCES bot.reaction_role_mappings(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    sent_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (mapping_id, user_id)
);

CREATE TABLE IF NOT EXISTS bot.schema_version (
    version INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS bot.server_faq_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMPTZ DEFAULT now(),
    guild_id BIGINT,
    channel_id BIGINT,
    user_id BIGINT,
    question TEXT NOT NULL,
    answer TEXT,
    model TEXT,
    metadata JSONB
);

CREATE INDEX IF NOT EXISTS server_faq_logs_created_at_idx
    ON bot.server_faq_logs (created_at);

CREATE TABLE IF NOT EXISTS bot.standalone_bot_state (
    bot TEXT PRIMARY KEY,
    heartbeat TIMESTAMPTZ NOT NULL,
    payload JSONB,
    updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS bot.standalone_commands (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bot TEXT NOT NULL,
    command TEXT NOT NULL,
    payload JSONB,
    status TEXT NOT NULL DEFAULT 'pending',
    result JSONB,
    error TEXT,
    created_at TIMESTAMPTZ DEFAULT now(),
    started_at TIMESTAMPTZ,
    finished_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS standalone_commands_status_idx
    ON bot.standalone_commands (status, created_at);

CREATE TABLE IF NOT EXISTS bot.streamer_link_intents (
    discord_id BIGINT PRIMARY KEY,
    discord_name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    linked_login TEXT
);

CREATE INDEX IF NOT EXISTS streamer_link_intents_pending_idx
    ON bot.streamer_link_intents (expires_at, created_at DESC)
    WHERE status = 'pending';

CREATE TABLE IF NOT EXISTS bot.tournament_periods (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    name TEXT NOT NULL,
    registration_start TIMESTAMPTZ NOT NULL,
    registration_end TIMESTAMPTZ NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    team_size INTEGER NOT NULL DEFAULT 6,
    created_by BIGINT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS tournament_periods_guild_active_idx
    ON bot.tournament_periods (guild_id, is_active);

CREATE TABLE IF NOT EXISTS bot.turnier_auth_tokens (
    token TEXT PRIMARY KEY,
    user_id BIGINT NOT NULL,
    display_name TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS turnier_auth_tokens_expires_at_idx
    ON bot.turnier_auth_tokens (expires_at);

CREATE TABLE IF NOT EXISTS bot.twitch_streamer_invites (
    streamer_login TEXT PRIMARY KEY,
    guild_id BIGINT,
    invite_code TEXT,
    invite_url TEXT,
    created_at TIMESTAMPTZ,
    last_sent_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS twitch_streamer_invites_guild_code_idx
    ON bot.twitch_streamer_invites (guild_id, invite_code);
