CREATE SCHEMA IF NOT EXISTS clips;

CREATE TABLE IF NOT EXISTS clips.clip_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    link TEXT NOT NULL,
    credit TEXT NOT NULL,
    permission TEXT NOT NULL,
    info TEXT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS clip_submissions_guild_idx
    ON clips.clip_submissions (guild_id);

CREATE INDEX IF NOT EXISTS clip_submissions_user_idx
    ON clips.clip_submissions (user_id);

CREATE TABLE IF NOT EXISTS clips.clip_windows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL DEFAULT 'running',
    dump_sent_at TIMESTAMPTZ,
    UNIQUE (guild_id, start_at, end_at)
);

CREATE INDEX IF NOT EXISTS clip_windows_guild_idx
    ON clips.clip_windows (guild_id);

CREATE INDEX IF NOT EXISTS clip_windows_active_idx
    ON clips.clip_windows (guild_id, start_at, end_at);

CREATE TABLE IF NOT EXISTS clips.clip_window_submissions (
    window_id BIGINT NOT NULL REFERENCES clips.clip_windows(id) ON DELETE CASCADE,
    submission_id BIGINT NOT NULL REFERENCES clips.clip_submissions(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (window_id, submission_id)
);

CREATE INDEX IF NOT EXISTS clip_window_submissions_user_idx
    ON clips.clip_window_submissions (user_id);

CREATE TABLE IF NOT EXISTS clips.clip_contests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    name TEXT,
    start_at TIMESTAMPTZ NOT NULL,
    end_at TIMESTAMPTZ NOT NULL,
    announce_channel_id BIGINT,
    status TEXT NOT NULL DEFAULT 'scheduled',
    video_url TEXT,
    winner_user_id BIGINT,
    created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS clip_contests_guild_idx
    ON clips.clip_contests (guild_id);

CREATE INDEX IF NOT EXISTS clip_contests_active_idx
    ON clips.clip_contests (guild_id, start_at, end_at);

CREATE TABLE IF NOT EXISTS clips.clip_contest_submissions (
    contest_id BIGINT NOT NULL REFERENCES clips.clip_contests(id) ON DELETE CASCADE,
    submission_id BIGINT NOT NULL REFERENCES clips.clip_submissions(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    PRIMARY KEY (contest_id, submission_id)
);

CREATE INDEX IF NOT EXISTS clip_contest_submissions_user_idx
    ON clips.clip_contest_submissions (user_id);

CREATE TABLE IF NOT EXISTS clips.clip_fetch_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    streamer_login TEXT NOT NULL,
    fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    clips_found INTEGER DEFAULT 0,
    clips_new INTEGER DEFAULT 0,
    fetch_duration_ms INTEGER,
    error TEXT
);

CREATE INDEX IF NOT EXISTS clip_fetch_history_streamer_idx
    ON clips.clip_fetch_history (streamer_login, fetched_at DESC);

CREATE TABLE IF NOT EXISTS clips.clip_last_hashtags (
    streamer_login TEXT PRIMARY KEY,
    hashtags JSONB NOT NULL,
    last_used_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS clips.clip_templates_global (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_name TEXT NOT NULL UNIQUE,
    description_template TEXT NOT NULL,
    hashtags JSONB NOT NULL,
    category TEXT,
    usage_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT now(),
    created_by TEXT
);

CREATE INDEX IF NOT EXISTS clip_templates_global_category_idx
    ON clips.clip_templates_global (category);

CREATE TABLE IF NOT EXISTS clips.clip_templates_streamer (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    streamer_login TEXT NOT NULL,
    template_name TEXT NOT NULL,
    description_template TEXT NOT NULL,
    hashtags JSONB NOT NULL,
    is_default BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT now(),
    updated_at TIMESTAMPTZ DEFAULT now(),
    UNIQUE (streamer_login, template_name)
);

CREATE INDEX IF NOT EXISTS clip_templates_streamer_login_idx
    ON clips.clip_templates_streamer (streamer_login);
