CREATE SCHEMA IF NOT EXISTS turnier;

CREATE TABLE IF NOT EXISTS turnier."audit_log" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "action" TEXT NOT NULL,
    "user_id" BIGINT,
    "details" JSONB,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."bracket_matches" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tournament_id" BIGINT NOT NULL,
    "round" BIGINT NOT NULL,
    "position" BIGINT NOT NULL,
    "bracket_type" TEXT NOT NULL,
    "team1_id" BIGINT,
    "team2_id" BIGINT,
    "winner_id" BIGINT,
    "status" TEXT NOT NULL,
    "steam_party_id" TEXT,
    "party_code" TEXT,
    "deadlock_match_id" TEXT,
    "scheduled_at" TIMESTAMPTZ,
    "played_at" TIMESTAMPTZ,
    "match_duration_s" BIGINT,
    "match_stats" JSONB,
    "source_match1_id" BIGINT,
    "source_match2_id" BIGINT,
    "discord_channel_id" BIGINT,
    "mini_group_id" BIGINT,
    "source_mini_group1_id" BIGINT,
    "source_mini_group2_id" BIGINT,
    "hero_assignments" JSONB,
    "loser_to_match_id" BIGINT,
    "loser_to_slot" BIGINT,
    "on_stream" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."bracket_mini_group_teams" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "mini_group_id" BIGINT NOT NULL,
    "team_id" BIGINT,
    "seed_order" BIGINT NOT NULL,
    "source_match_id" BIGINT,
    "source_mini_group_id" BIGINT
);

CREATE TABLE IF NOT EXISTS turnier."bracket_mini_groups" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tournament_id" BIGINT NOT NULL,
    "round" BIGINT NOT NULL,
    "position" BIGINT NOT NULL,
    "advances_to_match_id" BIGINT,
    "advances_to_slot" BIGINT,
    "created_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS turnier."checkins" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "match_type" TEXT NOT NULL,
    "match_id" BIGINT NOT NULL,
    "team_id" BIGINT NOT NULL,
    "discord_id" BIGINT NOT NULL,
    "checked_in_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."discord_tasks" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "type" TEXT NOT NULL,
    "payload" JSONB,
    "status" TEXT,
    "result_payload" JSONB,
    "error" TEXT,
    "created_at" TIMESTAMPTZ,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS turnier."draft_actions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "session_id" BIGINT NOT NULL,
    "sequence_index" BIGINT NOT NULL,
    "action_type" TEXT NOT NULL,
    "team_slot" BIGINT NOT NULL,
    "hero_name" TEXT,
    "taken_by" BIGINT,
    "taken_at" TIMESTAMPTZ,
    "is_admin_forced" BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."draft_sessions" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "bracket_match_id" BIGINT NOT NULL,
    "status" TEXT NOT NULL,
    "current_action_index" BIGINT NOT NULL,
    "started_by" BIGINT,
    "started_at" TIMESTAMPTZ,
    "completed_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."group_matches" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "group_id" BIGINT NOT NULL,
    "team1_id" BIGINT NOT NULL,
    "team2_id" BIGINT NOT NULL,
    "winner_id" BIGINT,
    "status" TEXT NOT NULL,
    "scheduled_at" TIMESTAMPTZ,
    "played_at" TIMESTAMPTZ,
    "discord_channel_id" BIGINT,
    "steam_party_id" TEXT,
    "party_code" TEXT,
    "deadlock_match_id" TEXT,
    "match_duration_s" BIGINT,
    "match_stats" JSONB,
    "hero_assignments" JSONB
);

CREATE TABLE IF NOT EXISTS turnier."group_teams" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "group_id" BIGINT NOT NULL,
    "team_id" BIGINT NOT NULL,
    "wins" BIGINT NOT NULL,
    "losses" BIGINT NOT NULL,
    "points" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."groups" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tournament_id" BIGINT NOT NULL,
    "name" TEXT NOT NULL,
    "seeding_order" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."match_casters" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "match_id" BIGINT NOT NULL,
    "match_type" TEXT NOT NULL,
    "discord_id" BIGINT NOT NULL,
    "assigned_at" TIMESTAMPTZ NOT NULL,
    "assigned_by" BIGINT
);

CREATE TABLE IF NOT EXISTS turnier."match_games" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "bracket_match_id" BIGINT NOT NULL,
    "game_number" BIGINT NOT NULL,
    "status" TEXT NOT NULL,
    "steam_party_id" TEXT,
    "party_code" TEXT,
    "deadlock_match_id" TEXT,
    "winner_team" BIGINT,
    "duration_s" BIGINT,
    "match_stats" JSONB,
    "created_at" TIMESTAMPTZ NOT NULL,
    "completed_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS turnier."match_result_reports" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "match_type" TEXT NOT NULL,
    "match_id" BIGINT NOT NULL,
    "tournament_id" BIGINT NOT NULL,
    "reported_by" BIGINT NOT NULL,
    "winner_team_id" BIGINT,
    "deadlock_match_id" TEXT,
    "is_no_show" BOOLEAN NOT NULL,
    "no_show_team_id" BIGINT,
    "status" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "resolved_at" TIMESTAMPTZ,
    "resolved_by" BIGINT
);

CREATE TABLE IF NOT EXISTS turnier."match_results" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "bracket_match_id" BIGINT,
    "group_match_id" BIGINT,
    "winning_team" BIGINT,
    "duration_s" BIGINT,
    "player_stats" JSONB,
    "source" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."player_points" (
    "discord_id" BIGINT PRIMARY KEY,
    "total_points" BIGINT NOT NULL,
    "tournaments_played" BIGINT NOT NULL,
    "matches_played" BIGINT NOT NULL,
    "matches_won" BIGINT NOT NULL,
    "best_placement" BIGINT,
    "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."rank_cache" (
    "discord_id" BIGINT PRIMARY KEY,
    "source" TEXT NOT NULL,
    "steam_id" TEXT,
    "rank" TEXT,
    "rank_tier" BIGINT,
    "subrank" BIGINT,
    "rank_score" BIGINT,
    "cached_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."sent_match_reminders" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "match_type" TEXT NOT NULL,
    "match_id" BIGINT NOT NULL,
    "kind" TEXT NOT NULL,
    "sent_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."sent_start_reminders" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tournament_id" BIGINT NOT NULL,
    "offset_minutes" BIGINT NOT NULL,
    "sent_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."sent_tournament_reminders" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tournament_id" BIGINT NOT NULL,
    "offset_minutes" BIGINT NOT NULL,
    "sent_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."sessions" (
    "token" TEXT PRIMARY KEY,
    "discord_id" BIGINT NOT NULL,
    "discord_name" TEXT,
    "discord_avatar" TEXT,
    "discord_roles" TEXT,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."team_applications" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "team_id" BIGINT NOT NULL,
    "discord_id" BIGINT NOT NULL,
    "discord_name" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."team_invitations" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tournament_id" BIGINT NOT NULL,
    "team_id" BIGINT NOT NULL,
    "discord_id" BIGINT NOT NULL,
    "signup_id" BIGINT,
    "status" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "expires_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS turnier."team_members" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "team_id" BIGINT NOT NULL,
    "discord_id" BIGINT NOT NULL,
    "discord_name" TEXT,
    "steam_id" TEXT,
    "rank" TEXT,
    "rank_score" BIGINT,
    "role" TEXT NOT NULL,
    "joined_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."teams" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tournament_id" BIGINT NOT NULL,
    "name" TEXT NOT NULL,
    "name_key" TEXT NOT NULL,
    "captain_discord_id" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "recruitment_status" TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."tournament_casters" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tournament_id" BIGINT NOT NULL,
    "discord_id" BIGINT NOT NULL,
    "assigned_at" TIMESTAMPTZ NOT NULL,
    "assigned_by" BIGINT
);

CREATE TABLE IF NOT EXISTS turnier."tournament_checkins" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tournament_id" BIGINT NOT NULL,
    "discord_id" BIGINT NOT NULL,
    "checked_in_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."tournament_dm_optout" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "discord_id" BIGINT NOT NULL,
    "scope" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."tournament_presets" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "team_size" BIGINT NOT NULL,
    "bracket_format" TEXT NOT NULL,
    "series_format" BIGINT NOT NULL,
    "final_series_format" BIGINT,
    "tournament_mode" TEXT NOT NULL,
    "tournament_game_mode" TEXT NOT NULL,
    "match_objective" TEXT NOT NULL,
    "invite_mode" TEXT NOT NULL,
    "reminder_offsets" JSONB,
    "start_reminder_offsets" JSONB,
    "rules" TEXT,
    "description_template" TEXT,
    "active" BOOLEAN NOT NULL,
    "created_by" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."tournament_proposal_feedback" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "proposal_id" BIGINT NOT NULL,
    "caster_discord_id" BIGINT NOT NULL,
    "raw_text" TEXT NOT NULL,
    "applied_change_json" JSONB,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."tournament_proposal_votes" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "proposal_id" BIGINT NOT NULL,
    "caster_discord_id" BIGINT NOT NULL,
    "decision" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."tournament_proposals" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "preset_id" BIGINT,
    "source" TEXT NOT NULL,
    "proposed_start" TIMESTAMPTZ,
    "config_json" JSONB NOT NULL,
    "state" TEXT NOT NULL,
    "proposal_message_id" BIGINT,
    "channel_id" BIGINT,
    "tournament_id" BIGINT,
    "decided_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."tournament_signals" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tournament_id" BIGINT NOT NULL,
    "participants" BIGINT,
    "teams" BIGINT,
    "no_shows" BIGINT,
    "poll_up" BIGINT,
    "poll_down" BIGINT,
    "poll_message_id" BIGINT,
    "feedback_summary" TEXT,
    "collected_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."tournament_signups" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tournament_id" BIGINT NOT NULL,
    "discord_id" BIGINT NOT NULL,
    "steam_id" TEXT,
    "rank" TEXT,
    "rank_score" BIGINT,
    "team_id" BIGINT,
    "signed_up_at" TIMESTAMPTZ NOT NULL,
    "discord_name" TEXT,
    "invited_by_team_id" BIGINT
);

CREATE TABLE IF NOT EXISTS turnier."tournaments" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "description" TEXT,
    "team_size" BIGINT NOT NULL,
    "registration_start" TIMESTAMPTZ,
    "registration_end" TIMESTAMPTZ,
    "group_phase_start" TIMESTAMPTZ,
    "bracket_start" TIMESTAMPTZ,
    "bracket_format" TEXT NOT NULL,
    "created_by" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "invite_mode" TEXT NOT NULL,
    "invite_window_start" TIMESTAMPTZ,
    "invite_window_end" TIMESTAMPTZ,
    "lobby_settings" JSONB,
    "checkin_start" TIMESTAMPTZ,
    "tournament_mode" TEXT NOT NULL,
    "series_format" BIGINT NOT NULL,
    "exclude_from_leaderboard" BOOLEAN NOT NULL,
    "reminder_offsets" JSONB,
    "tournament_game_mode" TEXT NOT NULL,
    "auto_lobby_enabled" BOOLEAN NOT NULL,
    "is_test" BOOLEAN NOT NULL,
    "rules" TEXT,
    "final_series_format" BIGINT,
    "match_objective" TEXT NOT NULL,
    "no_show_grace_minutes" BIGINT NOT NULL,
    "start_reminder_offsets" JSONB,
    "scheduled_event_id" BIGINT,
    "source" TEXT NOT NULL,
    "preset_id" BIGINT
);

CREATE TABLE IF NOT EXISTS turnier."user_consents" (
    "discord_id" BIGINT PRIMARY KEY,
    "consented_at" TIMESTAMPTZ NOT NULL,
    "consent_version" BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS turnier."user_profiles" (
    "discord_id" BIGINT PRIMARY KEY,
    "bio" TEXT,
    "invite_auto_accept" BOOLEAN NOT NULL,
    "notify_discord_dm" BOOLEAN NOT NULL,
    "notify_browser" BOOLEAN NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL,
    "display_name" TEXT,
    "avatar_filename" TEXT,
    "notify_match_start" BOOLEAN NOT NULL,
    "notify_checkin" BOOLEAN NOT NULL,
    "notify_team_invite" BOOLEAN NOT NULL,
    "notify_tournament_news" BOOLEAN NOT NULL,
    "notify_registration_reminder" BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "ux_turnier_bmgt_seed_order"
    ON turnier."bracket_mini_group_teams" ("mini_group_id", "seed_order");

CREATE UNIQUE INDEX IF NOT EXISTS "ux_turnier_bmgt_team"
    ON turnier."bracket_mini_group_teams" ("mini_group_id", "team_id");

CREATE UNIQUE INDEX IF NOT EXISTS "ux_turnier_group_teams_group_team"
    ON turnier."group_teams" ("group_id", "team_id");

CREATE UNIQUE INDEX IF NOT EXISTS "ux_turnier_match_casters_match_type_discord"
    ON turnier."match_casters" ("match_id", "match_type", "discord_id");

CREATE UNIQUE INDEX IF NOT EXISTS "ux_turnier_match_games_match_game"
    ON turnier."match_games" ("bracket_match_id", "game_number");

CREATE UNIQUE INDEX IF NOT EXISTS "ux_turnier_sent_match_reminders_match_kind"
    ON turnier."sent_match_reminders" ("match_type", "match_id", "kind");

CREATE UNIQUE INDEX IF NOT EXISTS "ux_turnier_sent_start_reminders_tournament_offset"
    ON turnier."sent_start_reminders" ("tournament_id", "offset_minutes");

CREATE UNIQUE INDEX IF NOT EXISTS "ux_turnier_sent_tournament_reminders_tournament_offset"
    ON turnier."sent_tournament_reminders" ("tournament_id", "offset_minutes");

CREATE UNIQUE INDEX IF NOT EXISTS "ux_turnier_team_applications_team_discord"
    ON turnier."team_applications" ("team_id", "discord_id");

CREATE UNIQUE INDEX IF NOT EXISTS "ux_turnier_team_invitations_team_discord"
    ON turnier."team_invitations" ("team_id", "discord_id");

CREATE UNIQUE INDEX IF NOT EXISTS "ux_turnier_team_members_team_discord"
    ON turnier."team_members" ("team_id", "discord_id");

CREATE UNIQUE INDEX IF NOT EXISTS "ux_turnier_teams_tournament_name_key"
    ON turnier."teams" ("tournament_id", "name_key");

CREATE UNIQUE INDEX IF NOT EXISTS "ux_turnier_tournament_casters_tournament_discord"
    ON turnier."tournament_casters" ("tournament_id", "discord_id");

CREATE UNIQUE INDEX IF NOT EXISTS "ux_turnier_tournament_checkins_tournament_discord"
    ON turnier."tournament_checkins" ("tournament_id", "discord_id");

CREATE UNIQUE INDEX IF NOT EXISTS "ux_turnier_tournament_dm_optout_discord_scope"
    ON turnier."tournament_dm_optout" ("discord_id", "scope");

CREATE UNIQUE INDEX IF NOT EXISTS "ux_turnier_tournament_proposal_votes_proposal_caster"
    ON turnier."tournament_proposal_votes" ("proposal_id", "caster_discord_id");

CREATE UNIQUE INDEX IF NOT EXISTS "ux_turnier_tournament_signups_tournament_discord"
    ON turnier."tournament_signups" ("tournament_id", "discord_id");

CREATE INDEX IF NOT EXISTS "ix_turnier_audit_log_created_at"
    ON turnier."audit_log" ("created_at");

CREATE INDEX IF NOT EXISTS "ix_turnier_audit_log_user_id"
    ON turnier."audit_log" ("user_id");

CREATE INDEX IF NOT EXISTS "ix_turnier_bracket_matches_tournament_id"
    ON turnier."bracket_matches" ("tournament_id");

CREATE INDEX IF NOT EXISTS "ix_turnier_bracket_matches_status"
    ON turnier."bracket_matches" ("status");

CREATE INDEX IF NOT EXISTS "ix_turnier_discord_tasks_status"
    ON turnier."discord_tasks" ("status");

CREATE INDEX IF NOT EXISTS "ix_turnier_discord_tasks_created_at"
    ON turnier."discord_tasks" ("created_at");

CREATE INDEX IF NOT EXISTS "ix_turnier_group_matches_group_id"
    ON turnier."group_matches" ("group_id");

CREATE INDEX IF NOT EXISTS "ix_turnier_group_matches_status"
    ON turnier."group_matches" ("status");

CREATE INDEX IF NOT EXISTS "ix_turnier_match_result_reports_tournament_id"
    ON turnier."match_result_reports" ("tournament_id");

CREATE INDEX IF NOT EXISTS "ix_turnier_match_result_reports_status"
    ON turnier."match_result_reports" ("status");

CREATE INDEX IF NOT EXISTS "ix_turnier_rank_cache_cached_at"
    ON turnier."rank_cache" ("cached_at");

CREATE INDEX IF NOT EXISTS "ix_turnier_sessions_discord_id"
    ON turnier."sessions" ("discord_id");

CREATE INDEX IF NOT EXISTS "ix_turnier_sessions_expires_at"
    ON turnier."sessions" ("expires_at");

CREATE INDEX IF NOT EXISTS "ix_turnier_team_members_discord_id"
    ON turnier."team_members" ("discord_id");

CREATE INDEX IF NOT EXISTS "ix_turnier_teams_tournament_id"
    ON turnier."teams" ("tournament_id");

CREATE INDEX IF NOT EXISTS "ix_turnier_tournament_signups_discord_id"
    ON turnier."tournament_signups" ("discord_id");

CREATE INDEX IF NOT EXISTS "ix_turnier_tournament_signups_team_id"
    ON turnier."tournament_signups" ("team_id");

CREATE INDEX IF NOT EXISTS "ix_turnier_tournaments_status"
    ON turnier."tournaments" ("status");

CREATE INDEX IF NOT EXISTS "ix_turnier_tournaments_created_at"
    ON turnier."tournaments" ("created_at");
