ALTER TABLE patchnotes.changelog_posts
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
    pg_get_serial_sequence('patchnotes.changelog_posts', 'id'),
    COALESCE((SELECT MAX(id) FROM patchnotes.changelog_posts), 0) + 1,
    false
);

ALTER TABLE patchnotes.deadlock_changelogs
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
    pg_get_serial_sequence('patchnotes.deadlock_changelogs', 'id'),
    COALESCE((SELECT MAX(id) FROM patchnotes.deadlock_changelogs), 0) + 1,
    false
);
