CREATE TABLE IF NOT EXISTS scrim.match_request_reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL DEFAULT 'missing_response_reminder'
        CHECK (action IN ('missing_response_reminder')),
    request_id INTEGER NOT NULL REFERENCES scrim.match_requests(id) ON DELETE CASCADE,
    team_id INTEGER NOT NULL REFERENCES scrim.teams(id) ON DELETE CASCADE,
    template TEXT NOT NULL DEFAULT 'antwort_fehlt'
        CHECK (template IN ('antwort_fehlt', 'frist_bald', 'bestaetigung_offen')),
    target_kind TEXT NOT NULL CHECK (target_kind IN ('members', 'team')),
    target_participant_ids INTEGER[] NOT NULL DEFAULT '{}',
    target_discord_user_ids BIGINT[] NOT NULL DEFAULT '{}',
    target_role_id BIGINT,
    missing_count INTEGER NOT NULL CHECK (missing_count >= 0),
    approved_by_user_id TEXT NOT NULL,
    approved_by_display_name TEXT NOT NULL,
    approved_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    scheduled_for TIMESTAMPTZ NOT NULL DEFAULT now(),
    status TEXT NOT NULL DEFAULT 'approved'
        CHECK (status IN ('approved', 'posting', 'posted', 'failed', 'cancelled')),
    discord_channel_id BIGINT NOT NULL,
    source_message_id BIGINT NOT NULL,
    discord_message_id BIGINT,
    last_error TEXT,
    posted_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS match_request_reminders_status_due_idx
    ON scrim.match_request_reminders (status, scheduled_for, id);

CREATE INDEX IF NOT EXISTS match_request_reminders_request_team_idx
    ON scrim.match_request_reminders (request_id, team_id, approved_at DESC);
