ALTER TABLE activity.journey_events
    DROP CONSTRAINT IF EXISTS journey_events_event_type_chk;

ALTER TABLE activity.journey_events
    ADD CONSTRAINT journey_events_event_type_chk CHECK (
        event_type IN (
            'join',
            'screening_completed',
            'native_onboarding_completed',
            'weiche_changed',
            'steam_link',
            'invite_friend_request_sent',
            'invite_friend_request_accepted',
            'invite_sent',
            'invite_accepted',
            'first_message',
            'first_voice',
            'first_match',
            'squad_join',
            'opt_out',
            'streamer_contact_activation',
            'd7_activity',
            'd14_activity',
            'concierge_t0_sent',
            'concierge_reply',
            'concierge_tour_done',
            'steckbrief_posted',
            'nudge_sent',
            'pate_offered',
            'opted_out',
            'congrats_sent'
        )
    );

CREATE TABLE IF NOT EXISTS bot.concierge_profiles (
    user_id BIGINT PRIMARY KEY,
    guild_id BIGINT NOT NULL,
    intent TEXT CHECK (intent IS NULL OR intent IN ('improve', 'mates', 'learn', 'casual')),
    rank_snapshot TEXT,
    play_times TEXT,
    funnel_status TEXT NOT NULL DEFAULT 'new',
    steckbrief_posted BOOLEAN NOT NULL DEFAULT FALSE,
    tour_done BOOLEAN NOT NULL DEFAULT FALSE,
    pate_offered BOOLEAN NOT NULL DEFAULT FALSE,
    pate_requested BOOLEAN NOT NULL DEFAULT FALSE,
    opted_out BOOLEAN NOT NULL DEFAULT FALSE,
    forgot_at TIMESTAMPTZ,
    unsolicited_contact_count INTEGER NOT NULL DEFAULT 0 CHECK (unsolicited_contact_count BETWEEN 0 AND 3),
    t0_sent_at TIMESTAMPTZ,
    t2_sent_at TIMESTAMPTZ,
    t7_sent_at TIMESTAMPTZ,
    congrats_sent_at TIMESTAMPTZ,
    first_message_at TIMESTAMPTZ,
    first_voice_at TIMESTAMPTZ,
    fallback_channel_id BIGINT,
    pending_steckbrief_text TEXT,
    pending_steckbrief_channel_id BIGINT,
    pending_steckbrief_requested_at TIMESTAMPTZ,
    last_interaction_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS concierge_profiles_guild_updated_idx
    ON bot.concierge_profiles (guild_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS concierge_profiles_pending_steckbrief_idx
    ON bot.concierge_profiles (pending_steckbrief_requested_at)
    WHERE pending_steckbrief_text IS NOT NULL;

CREATE TABLE IF NOT EXISTS bot.concierge_conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    guild_id BIGINT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('system', 'user', 'assistant')),
    content TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS concierge_conversations_user_created_idx
    ON bot.concierge_conversations (user_id, created_at DESC);
