ALTER TABLE bot.twitch_streamer_invites
    ADD COLUMN IF NOT EXISTS twitch_user_id TEXT,
    ADD COLUMN IF NOT EXISTS active_partner BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS twitch_streamer_invites_twitch_user_idx
    ON bot.twitch_streamer_invites (twitch_user_id)
    WHERE twitch_user_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS bot.twitch_personal_invites (
    streamer_login TEXT NOT NULL,
    inviter_twitch_user_id TEXT NOT NULL,
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    invite_code TEXT NOT NULL,
    invite_url TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (streamer_login, inviter_twitch_user_id),
    UNIQUE (guild_id, invite_code)
);

CREATE INDEX IF NOT EXISTS twitch_personal_invites_channel_idx
    ON bot.twitch_personal_invites (guild_id, channel_id);

CREATE TABLE IF NOT EXISTS bot.twitch_invite_program (
    singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
    started_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO bot.twitch_invite_program(singleton)
VALUES (TRUE)
ON CONFLICT (singleton) DO NOTHING;

CREATE TABLE IF NOT EXISTS activity.twitch_invite_qualifications (
    join_event_id BIGINT PRIMARY KEY REFERENCES activity.member_events(id) ON DELETE RESTRICT,
    user_id BIGINT NOT NULL,
    guild_id BIGINT NOT NULL,
    streamer_login TEXT NOT NULL,
    inviter_twitch_user_id TEXT,
    invite_code TEXT,
    joined_at TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending',
    qualified_at TIMESTAMPTZ,
    expired_at TIMESTAMPTZ,
    last_evaluated_at TIMESTAMPTZ,
    UNIQUE (user_id, guild_id),
    CONSTRAINT twitch_invite_qualifications_status_chk
        CHECK (status IN ('pending', 'qualified', 'expired')),
    CONSTRAINT twitch_invite_qualifications_terminal_time_chk
        CHECK (
            (status = 'pending' AND qualified_at IS NULL AND expired_at IS NULL)
            OR (status = 'qualified' AND qualified_at IS NOT NULL AND expired_at IS NULL)
            OR (status = 'expired' AND qualified_at IS NULL AND expired_at IS NOT NULL)
        )
);

CREATE INDEX IF NOT EXISTS twitch_invite_qualifications_status_joined_idx
    ON activity.twitch_invite_qualifications (status, joined_at);

CREATE INDEX IF NOT EXISTS twitch_invite_qualifications_streamer_joined_idx
    ON activity.twitch_invite_qualifications (streamer_login, joined_at DESC);

CREATE TABLE IF NOT EXISTS activity.twitch_invite_qualification_transitions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    join_event_id BIGINT NOT NULL REFERENCES activity.twitch_invite_qualifications(join_event_id) ON DELETE RESTRICT,
    from_status TEXT,
    to_status TEXT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT twitch_invite_qualification_transitions_from_chk
        CHECK (from_status IS NULL OR from_status IN ('pending', 'qualified', 'expired')),
    CONSTRAINT twitch_invite_qualification_transitions_to_chk
        CHECK (to_status IN ('pending', 'qualified', 'expired'))
);

CREATE INDEX IF NOT EXISTS twitch_invite_qualification_transitions_join_idx
    ON activity.twitch_invite_qualification_transitions (join_event_id, occurred_at);

CREATE TABLE IF NOT EXISTS activity.streamer_referral_credits (
    join_event_id BIGINT PRIMARY KEY REFERENCES activity.member_events(id) ON DELETE RESTRICT,
    invited_discord_user_id BIGINT NOT NULL,
    guild_id BIGINT NOT NULL,
    inviter_twitch_user_id TEXT NOT NULL,
    invited_twitch_user_id TEXT NOT NULL,
    invited_twitch_login TEXT NOT NULL,
    credited_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    credit_type TEXT NOT NULL DEFAULT 'streamer_referral',
    UNIQUE (invited_twitch_user_id),
    CONSTRAINT streamer_referral_credits_type_chk
        CHECK (credit_type = 'streamer_referral')
);

CREATE INDEX IF NOT EXISTS streamer_referral_credits_inviter_idx
    ON activity.streamer_referral_credits (inviter_twitch_user_id, credited_at DESC);
