CREATE TABLE IF NOT EXISTS activity.journey_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    guild_id BIGINT NOT NULL,
    event_type TEXT NOT NULL,
    event_source TEXT NOT NULL DEFAULT 'gateway',
    actor_kind TEXT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    channel_id BIGINT,
    message_id BIGINT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT journey_events_event_type_chk CHECK (
        event_type IN (
            'join',
            'screening_completed',
            'native_onboarding_completed',
            'weiche_changed',
            'steam_link',
            'invite_friend_request_sent',
            'invite_friend_request_accepted',
            'invite_sent',
            'invite_accepted',
            'first_message',
            'first_voice',
            'first_match',
            'squad_join',
            'opt_out',
            'streamer_contact_activation',
            'd7_activity',
            'd14_activity'
        )
    ),
    CONSTRAINT journey_events_actor_kind_chk CHECK (
        actor_kind IS NULL OR actor_kind IN ('human', 'bot', 'system')
    )
);

CREATE INDEX IF NOT EXISTS journey_events_user_occurred_idx
    ON activity.journey_events (user_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS journey_events_guild_type_occurred_idx
    ON activity.journey_events (guild_id, event_type, occurred_at DESC);

CREATE UNIQUE INDEX IF NOT EXISTS journey_events_first_event_uidx
    ON activity.journey_events (guild_id, user_id, event_type)
    WHERE event_type IN ('first_message', 'first_voice');

CREATE TABLE IF NOT EXISTS activity.journey_user_state (
    user_id BIGINT NOT NULL,
    guild_id BIGINT NOT NULL,
    joined_at TIMESTAMPTZ,
    screening_completed_at TIMESTAMPTZ,
    native_onboarding_completed_at TIMESTAMPTZ,
    weiche_choice TEXT,
    steam_linked_at TIMESTAMPTZ,
    invite_friend_request_sent_at TIMESTAMPTZ,
    invite_friend_request_accepted_at TIMESTAMPTZ,
    invite_sent_at TIMESTAMPTZ,
    invite_accepted_at TIMESTAMPTZ,
    invite_actor_kind TEXT,
    first_message_at TIMESTAMPTZ,
    first_voice_at TIMESTAMPTZ,
    first_match_at TIMESTAMPTZ,
    squad_joined_at TIMESTAMPTZ,
    first_interaction_at TIMESTAMPTZ,
    streamer_contact_activated_at TIMESTAMPTZ,
    opt_out_at TIMESTAMPTZ,
    last_event_at TIMESTAMPTZ,
    last_event_type TEXT,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, guild_id),
    CONSTRAINT journey_user_state_invite_actor_kind_chk CHECK (
        invite_actor_kind IS NULL OR invite_actor_kind IN ('human', 'bot', 'system')
    )
);

CREATE INDEX IF NOT EXISTS journey_user_state_guild_joined_idx
    ON activity.journey_user_state (guild_id, joined_at);

CREATE INDEX IF NOT EXISTS journey_user_state_guild_first_message_idx
    ON activity.journey_user_state (guild_id, first_message_at)
    WHERE first_message_at IS NOT NULL;

CREATE TABLE IF NOT EXISTS activity.message_metadata_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    message_id BIGINT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL,
    message_length INTEGER NOT NULL,
    has_attachment BOOLEAN NOT NULL,
    attachment_count INTEGER NOT NULL DEFAULT 0,
    is_reply BOOLEAN NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS message_metadata_events_message_uidx
    ON activity.message_metadata_events (guild_id, channel_id, message_id);

CREATE INDEX IF NOT EXISTS message_metadata_events_user_occurred_idx
    ON activity.message_metadata_events (user_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS message_metadata_events_guild_occurred_idx
    ON activity.message_metadata_events (guild_id, occurred_at DESC);

CREATE TABLE IF NOT EXISTS activity.voice_metadata_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    event_type TEXT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    duration_seconds BIGINT,
    from_channel_id BIGINT,
    to_channel_id BIGINT,
    CONSTRAINT voice_metadata_events_event_type_chk CHECK (
        event_type IN ('join', 'leave', 'move', 'update')
    )
);

CREATE INDEX IF NOT EXISTS voice_metadata_events_user_occurred_idx
    ON activity.voice_metadata_events (user_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS voice_metadata_events_guild_occurred_idx
    ON activity.voice_metadata_events (guild_id, occurred_at DESC);

CREATE TABLE IF NOT EXISTS activity.voice_open_sessions (
    user_id BIGINT NOT NULL,
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    joined_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, guild_id)
);

CREATE INDEX IF NOT EXISTS voice_open_sessions_joined_idx
    ON activity.voice_open_sessions (joined_at);

CREATE TABLE IF NOT EXISTS activity.interaction_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    guild_id BIGINT NOT NULL,
    channel_id BIGINT,
    message_id BIGINT,
    interaction_id BIGINT NOT NULL,
    interaction_kind TEXT NOT NULL,
    route TEXT,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT interaction_events_kind_chk CHECK (
        interaction_kind IN ('command', 'component', 'modal')
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS interaction_events_interaction_uidx
    ON activity.interaction_events (interaction_id);

CREATE INDEX IF NOT EXISTS interaction_events_user_occurred_idx
    ON activity.interaction_events (user_id, occurred_at DESC);

CREATE INDEX IF NOT EXISTS interaction_events_guild_occurred_idx
    ON activity.interaction_events (guild_id, occurred_at DESC);

CREATE TABLE IF NOT EXISTS activity.message_daily_aggregates (
    day DATE NOT NULL,
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    message_count BIGINT NOT NULL DEFAULT 0,
    total_message_length BIGINT NOT NULL DEFAULT 0,
    attachment_message_count BIGINT NOT NULL DEFAULT 0,
    reply_message_count BIGINT NOT NULL DEFAULT 0,
    distinct_user_count BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (day, guild_id, channel_id)
);

CREATE TABLE IF NOT EXISTS activity.voice_daily_aggregates (
    day DATE NOT NULL,
    guild_id BIGINT NOT NULL,
    channel_id BIGINT NOT NULL,
    join_count BIGINT NOT NULL DEFAULT 0,
    leave_count BIGINT NOT NULL DEFAULT 0,
    move_count BIGINT NOT NULL DEFAULT 0,
    update_count BIGINT NOT NULL DEFAULT 0,
    total_duration_seconds BIGINT NOT NULL DEFAULT 0,
    distinct_user_count BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (day, guild_id, channel_id)
);

CREATE TABLE IF NOT EXISTS activity.interaction_daily_aggregates (
    day DATE NOT NULL,
    guild_id BIGINT NOT NULL,
    interaction_kind TEXT NOT NULL,
    route TEXT NOT NULL DEFAULT '',
    interaction_count BIGINT NOT NULL DEFAULT 0,
    distinct_user_count BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (day, guild_id, interaction_kind, route)
);

CREATE TABLE IF NOT EXISTS activity.journey_daily_aggregates (
    day DATE NOT NULL,
    guild_id BIGINT NOT NULL,
    event_type TEXT NOT NULL,
    actor_kind TEXT NOT NULL DEFAULT '',
    event_count BIGINT NOT NULL DEFAULT 0,
    distinct_user_count BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (day, guild_id, event_type, actor_kind)
);
